spring.application.name=jono-transaction-lab

spring.datasource.url=jdbc:postgresql://localhost:5432/jono_transaction_lab
spring.datasource.username=naveen
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true